version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - wegnots-network

  monitor:
    build: .
    command: python api_server.py
    environment:
      - PYTHONUNBUFFERED=1
      # MongoDB
      - MONGODB_URI=mongodb://mongodb:27017/
      # Credenciais do arquivo .env
      - IMAP_SERVER=${IMAP_SERVER}
      - IMAP_PORT=${IMAP_PORT}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      # Configurações de Email
      - MONITORED_EMAILS=${MONITORED_EMAILS}
      # Configurações adicionais
      - CHECK_INTERVAL=${CHECK_INTERVAL:-60}
      - RECONNECT_ATTEMPTS=${RECONNECT_ATTEMPTS:-5}
      - RECONNECT_DELAY=${RECONNECT_DELAY:-30}
      - RECONNECT_BACKOFF_FACTOR=${RECONNECT_BACKOFF_FACTOR:-1.5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./config.ini
        target: /app/config.ini
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "monitor"
        tag: "monitor-service"
    security_opt:
      - no-new-privileges:true
    networks:
      - wegnots-network

volumes:
  mongodb_data:

networks:
  wegnots-network:
    driver: bridge
